SystemOrganization addCategory: #'Doyel-Facilitator'!
SystemOrganization addCategory: 'Doyel-Facilitator-Component'!
SystemOrganization addCategory: 'Doyel-Facilitator-Css'!
SystemOrganization addCategory: 'Doyel-Facilitator-Herramientas'!
SystemOrganization addCategory: 'Doyel-Facilitator-Modelo'!
SystemOrganization addCategory: 'Doyel-Facilitator-Session'!
SystemOrganization addCategory: 'Doyel-Facilitator-Test-Unidad'!
