style
style
	^ '
	.panel {
    text-shadow: 0 1px 0 rgba(255, 255, 255, .2);
    -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, .25), 0 1px 2px rgba(0, 0, 0, .05);
    box-shadow: inset 0 1px 0 rgba(255, 255, 255, .25), 0 1px 2px rgba(0, 0, 0, .05);
	}
	.panel-personalizado { 
		background-image: linear-gradient(to bottom, #d3acaf 0%, #e8e8e8 100%);
		background-repeat: repeat-x;
      border-color: #e8e8e8;
	 }	
	'